---

- hosts: all
  become: true
  tasks:

  - name: update and upgrade repo index
    apt:
      upgrade: yes
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: minecraft
  become: true
  roles:
    - minecraft